version: '3.8'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DATABASE_FILE=./data/silentcircle.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
